# URL to the Plex server
plex_url = "http://192.168.x.x:32400"

# How to find a token:
# https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
# You may also be able to find one by looking at Plex cookies.
# A token looks something like: fIHGeXfEbda_3X_AB123
plex_token = "..."

# Plex libraries to scan for shows and movies
# Note: Change this -- you will receive warnings for libraries that don't exist!
#
# If you want to hide summaries for unseen movies as well as TV episodes, add your movie library/libraries here!
libraries = ['TV Shows', 'TV Series']

# The text to show in Plex for episodes/movies with their summmary hidden.
#
# !! IMPORTANT !!
# In order to change this after you've used the script at least once, you should run --restore-all first, wait for
# Plex to re-download all metadata, and only *then* change this.
# If you simply change the text string, the script won't work properly, as it checks for this string to identify
# which episodes/movies we've hidden the summary from, and previously hidden episodes won't be recognized as such.
hidden_string = "Summary hidden."

# Whether we should lock the summaries we edit or not.
# Locked summaries won't be automatically overwritten by Plex when you refresh items.
# If this is set to false, refreshing metadata in Plex will restore all summaries.
#
# Use the script with the --restore-all argument (which ignores this setting) to restore and unlock all summaries.
lock_hidden_summaries = true

# You can specify a list of shows and movies to ignore.
# Ignored shows/movies always have their summaries visible.
# For example, you may want to show the summaries for shows you already know by heart,
# or for certain shows (like comedy shows) where the summary doesn't really spoil anything.
#
# Specify this as a TOML multiline string. For example:
# ignored_items = """
# Seinfeld
# Stargate SG-1
# """

ignored_items = """
"""
